name: Stock Price Notifier # ワークフローの名前

on:
  workflow_dispatch: # 手動実行を許可する場合
  schedule:
    # 毎日午前9時 (JST) に実行
    # cronの時刻指定はUTCなので、JSTの午前9時はUTCの午前0時
    - cron: '0 0 * * *'

jobs:
  notify:
    runs-on: ubuntu-latest # 実行環境
    steps:
      - name: Checkout repository # リポジトリのコードをチェックアウト
        uses: actions/checkout@v4

      - name: Set up Python # Python環境をセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # 使用するPythonのバージョン

      - name: Install dependencies # 必要なライブラリをインストール
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz # slack_sdk は使わないので不要

      - name: Run script # Pythonスクリプトを実行
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # SecretsからWebhook URLを環境変数に設定
        run: python stock_notifier.py
